dist: xenial
services:
  - xvfb

env:
  global:
  - CODECLIMATE_REPO_TOKEN=a47935830d841ad61a6e960be8a3b6a5e557146ac010dafa993e61bf82898472

language: python

python:
- 3.6

addons:
  firefox: "49.0.2"

before_script:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - "export DISPLAY=:99.0"

script:
- python setup.py test
- codeclimate-test-reporter

notifications:
  email: false
